import { Template, InteractionType } from '@/types';

export const TEMPLATES: Template[] = [
  // Birthday
  {
    id: 'tpl_bday_1',
    slug: 'birthday-balloon-blast',
    title: 'Birthday Balloon Blast',
    description: 'A vibrant template featuring popable balloons and confetti.',
    occasion: 'birthday',
    category: 'fun',
    colorPalette: {
      primary: '#FF4B4B',
      secondary: '#4B9AFF',
      accent: '#FFD93D',
      background: '#FFF5F5',
      text: '#333333'
    },
    fontStyle: 'playful',
    animationType: 'confetti',
    interactiveModules: ['balloons', 'button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'Wishing you a day filled with joy, laughter, and endless surprises! May all your dreams take flight this year.',
    isPremium: false,
    isPublished: true,
    popularity: 95,
    tags: ['birthday', 'fun', 'balloons'],
    emoji: '🎈',
    previewGradient: 'linear-gradient(135deg, #FF4B4B, #4B9AFF)'
  },
  {
    id: 'tpl_bday_2',
    slug: 'blow-the-candles',
    title: 'Blow the Candles',
    description: 'An interactive cake where the recipient blows into the mic to blow out candles.',
    occasion: 'birthday',
    category: 'interactive',
    colorPalette: {
      primary: '#FF8A65',
      secondary: '#FFB74D',
      accent: '#FFF176',
      background: '#FAFAFA',
      text: '#424242'
    },
    fontStyle: 'elegant',
    animationType: 'fade',
    interactiveModules: ['audio', 'button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'Make a wish and blow out the candles! Here is to a brilliant year ahead filled with sweet moments.',
    isPremium: false,
    isPublished: true,
    popularity: 88,
    tags: ['birthday', 'cake', 'interactive'],
    emoji: '🎂',
    previewGradient: 'linear-gradient(135deg, #FF8A65, #FFB74D)'
  },
  {
    id: 'tpl_bday_3',
    slug: 'birthday-gift-box',
    title: 'Birthday Gift Box',
    description: 'Tap to unwrap a virtual gift box to reveal the message.',
    occasion: 'birthday',
    category: 'reveal',
    colorPalette: {
      primary: '#9C27B0',
      secondary: '#E040FB',
      accent: '#FF4081',
      background: '#F3E5F5',
      text: '#4A148C'
    },
    fontStyle: 'modern',
    animationType: 'bounce',
    interactiveModules: ['button', 'envelope'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature', 'images'],
    defaultMessage: 'A special gift just for you! Sending you all my love and best wishes on your special day.',
    isPremium: false,
    isPublished: true,
    popularity: 92,
    tags: ['birthday', 'gift', 'reveal'],
    emoji: '🎁',
    previewGradient: 'linear-gradient(135deg, #9C27B0, #E040FB)'
  },
  {
    id: 'tpl_bday_4',
    slug: 'birthday-photo-memories',
    title: 'Birthday Photo Memories',
    description: 'A beautiful slideshow of memories for a heartfelt wish.',
    occasion: 'birthday',
    category: 'emotional',
    colorPalette: {
      primary: '#3F51B5',
      secondary: '#7986CB',
      accent: '#FFC107',
      background: '#E8EAF6',
      text: '#1A237E'
    },
    fontStyle: 'elegant',
    animationType: 'slide',
    interactiveModules: ['gallery'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature', 'images'],
    defaultMessage: 'Looking back at all these wonderful moments we shared. Happy Birthday to someone truly special!',
    isPremium: false,
    isPublished: true,
    popularity: 90,
    tags: ['birthday', 'memories', 'photos'],
    emoji: '📸',
    previewGradient: 'linear-gradient(135deg, #3F51B5, #7986CB)'
  },
  {
    id: 'tpl_bday_5',
    slug: 'funny-birthday-challenge',
    title: 'Funny Birthday Challenge',
    description: 'A humorous template with a mini-game before the wish.',
    occasion: 'birthday',
    category: 'fun',
    colorPalette: {
      primary: '#00BCD4',
      secondary: '#4DD0E1',
      accent: '#FFEB3B',
      background: '#E0F7FA',
      text: '#006064'
    },
    fontStyle: 'playful',
    animationType: 'bounce',
    interactiveModules: ['quiz'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'You are another year older, but let us pretend you are still young! Have a hilarious birthday!',
    isPremium: false,
    isPublished: true,
    popularity: 85,
    tags: ['birthday', 'funny', 'game'],
    emoji: '😂',
    previewGradient: 'linear-gradient(135deg, #00BCD4, #4DD0E1)'
  },

  // Anniversary/Romance
  {
    id: 'tpl_anniv_1',
    slug: 'our-story',
    title: 'Our Story',
    description: 'A romantic scrolling narrative of your journey together.',
    occasion: 'anniversary',
    category: 'emotional',
    colorPalette: {
      primary: '#E91E63',
      secondary: '#F06292',
      accent: '#FF9800',
      background: '#FCE4EC',
      text: '#880E4F'
    },
    fontStyle: 'elegant',
    animationType: 'fade',
    interactiveModules: ['timeline', 'gallery'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature', 'images'],
    defaultMessage: 'Every chapter with you is my favorite. Here is to our beautiful story and the many pages yet to be written.',
    isPremium: false,
    isPublished: true,
    popularity: 94,
    tags: ['anniversary', 'romance', 'story'],
    emoji: '📖',
    previewGradient: 'linear-gradient(135deg, #E91E63, #F06292)'
  },
  {
    id: 'tpl_anniv_2',
    slug: 'blooming-roses',
    title: 'Blooming Roses',
    description: 'Watch digital roses bloom as the message is revealed.',
    occasion: 'anniversary',
    category: 'romantic',
    colorPalette: {
      primary: '#D32F2F',
      secondary: '#EF5350',
      accent: '#FFCDD2',
      background: '#FFEBEE',
      text: '#B71C1C'
    },
    fontStyle: 'elegant',
    animationType: 'fade',
    interactiveModules: ['button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'My love for you grows more beautiful with each passing day. Happy Anniversary, my darling.',
    isPremium: false,
    isPublished: true,
    popularity: 91,
    tags: ['anniversary', 'roses', 'love'],
    emoji: '🌹',
    previewGradient: 'linear-gradient(135deg, #D32F2F, #EF5350)'
  },
  {
    id: 'tpl_anniv_3',
    slug: 'love-letter',
    title: 'Love Letter',
    description: 'A classic virtual envelope that opens into a handwritten note.',
    occasion: 'romance',
    category: 'classic',
    colorPalette: {
      primary: '#8D6E63',
      secondary: '#BCAAA4',
      accent: '#EFEBE9',
      background: '#F5F5F5',
      text: '#3E2723'
    },
    fontStyle: 'handwritten',
    animationType: 'slide',
    interactiveModules: ['envelope'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'I just wanted to remind you how much you mean to me. You are my everything.',
    isPremium: false,
    isPublished: true,
    popularity: 89,
    tags: ['romance', 'letter', 'classic'],
    emoji: '💌',
    previewGradient: 'linear-gradient(135deg, #8D6E63, #BCAAA4)'
  },
  {
    id: 'tpl_anniv_4',
    slug: 'relationship-timeline',
    title: 'Relationship Timeline',
    description: 'Highlight key milestones in your relationship.',
    occasion: 'anniversary',
    category: 'emotional',
    colorPalette: {
      primary: '#009688',
      secondary: '#4DB6AC',
      accent: '#B2DFDB',
      background: '#E0F2F1',
      text: '#004D40'
    },
    fontStyle: 'modern',
    animationType: 'fade',
    interactiveModules: ['timeline'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature', 'timeline'],
    defaultMessage: 'From our first date to this amazing moment, I cherish every second spent with you.',
    isPremium: false,
    isPublished: true,
    popularity: 86,
    tags: ['anniversary', 'timeline', 'milestones'],
    emoji: '⏳',
    previewGradient: 'linear-gradient(135deg, #009688, #4DB6AC)'
  },
  {
    id: 'tpl_anniv_5',
    slug: 'proposal-reveal',
    title: 'Proposal Reveal',
    description: 'A suspenseful, slow reveal perfect for a big question.',
    occasion: 'romance',
    category: 'reveal',
    colorPalette: {
      primary: '#FFD700',
      secondary: '#FBC02D',
      accent: '#FFF9C4',
      background: '#111111',
      text: '#FFFFFF'
    },
    fontStyle: 'elegant',
    animationType: 'bounce',
    interactiveModules: ['scratch'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'There is something very important I need to ask you...',
    isPremium: false,
    isPublished: true,
    popularity: 96,
    tags: ['proposal', 'reveal', 'ring'],
    emoji: '💍',
    previewGradient: 'linear-gradient(135deg, #FFD700, #FBC02D)'
  },

  // Celebration
  {
    id: 'tpl_celeb_1',
    slug: 'congratulations-confetti',
    title: 'Congratulations Confetti',
    description: 'A burst of confetti and cheerful colors to celebrate an achievement.',
    occasion: 'celebration',
    category: 'fun',
    colorPalette: {
      primary: '#4CAF50',
      secondary: '#81C784',
      accent: '#FFEB3B',
      background: '#E8F5E9',
      text: '#1B5E20'
    },
    fontStyle: 'bold',
    animationType: 'confetti',
    interactiveModules: ['button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'You did it! I am incredibly proud of your hard work and amazing success.',
    isPremium: false,
    isPublished: true,
    popularity: 93,
    tags: ['congratulations', 'success', 'confetti'],
    emoji: '🎉',
    previewGradient: 'linear-gradient(135deg, #4CAF50, #81C784)'
  },
  {
    id: 'tpl_celeb_2',
    slug: 'wedding-celebration',
    title: 'Wedding Celebration',
    description: 'An elegant layout for sending wedding wishes.',
    occasion: 'wedding',
    category: 'formal',
    colorPalette: {
      primary: '#607D8B',
      secondary: '#90A4AE',
      accent: '#ECEFF1',
      background: '#FAFAFA',
      text: '#263238'
    },
    fontStyle: 'elegant',
    animationType: 'fade',
    interactiveModules: ['envelope'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'Wishing you a lifetime of love and happiness together. Congratulations on your wedding!',
    isPremium: false,
    isPublished: true,
    popularity: 87,
    tags: ['wedding', 'marriage', 'formal'],
    emoji: '💒',
    previewGradient: 'linear-gradient(135deg, #607D8B, #90A4AE)'
  },
  {
    id: 'tpl_celeb_3',
    slug: 'new-home',
    title: 'New Home',
    description: 'A cozy template to congratulate someone on moving in.',
    occasion: 'celebration',
    category: 'casual',
    colorPalette: {
      primary: '#795548',
      secondary: '#A1887F',
      accent: '#D7CCC8',
      background: '#EFEBE9',
      text: '#3E2723'
    },
    fontStyle: 'modern',
    animationType: 'slide',
    interactiveModules: ['button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'May your new home be filled with warmth, love, and wonderful memories!',
    isPremium: false,
    isPublished: true,
    popularity: 82,
    tags: ['housewarming', 'home', 'cozy'],
    emoji: '🏠',
    previewGradient: 'linear-gradient(135deg, #795548, #A1887F)'
  },
  {
    id: 'tpl_celeb_4',
    slug: 'graduation-celebration',
    title: 'Graduation Celebration',
    description: 'A smart and inspiring theme for a new graduate.',
    occasion: 'celebration',
    category: 'formal',
    colorPalette: {
      primary: '#1976D2',
      secondary: '#64B5F6',
      accent: '#FFC107',
      background: '#E3F2FD',
      text: '#0D47A1'
    },
    fontStyle: 'bold',
    animationType: 'confetti',
    interactiveModules: ['button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'The tassel was worth the hassle! Cheers to your next big adventure.',
    isPremium: false,
    isPublished: true,
    popularity: 85,
    tags: ['graduation', 'success', 'school'],
    emoji: '🎓',
    previewGradient: 'linear-gradient(135deg, #1976D2, #64B5F6)'
  },
  {
    id: 'tpl_celeb_5',
    slug: 'new-baby',
    title: 'New Baby',
    description: 'A sweet and gentle template to welcome a little one.',
    occasion: 'celebration',
    category: 'emotional',
    colorPalette: {
      primary: '#F06292',
      secondary: '#64B5F6',
      accent: '#FFF59D',
      background: '#FFFDE7',
      text: '#424242'
    },
    fontStyle: 'playful',
    animationType: 'fade',
    interactiveModules: ['gallery'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'Welcome to the world, little one! Sending lots of love to the growing family.',
    isPremium: false,
    isPublished: true,
    popularity: 84,
    tags: ['baby', 'welcome', 'family'],
    emoji: '👶',
    previewGradient: 'linear-gradient(135deg, #F06292, #64B5F6)'
  },

  // Family
  {
    id: 'tpl_fam_1',
    slug: 'thank-you-mom',
    title: 'Thank You Mom',
    description: 'A beautiful floral tribute to motherly love.',
    occasion: 'family',
    category: 'emotional',
    colorPalette: {
      primary: '#AB47BC',
      secondary: '#CE93D8',
      accent: '#F8BBD0',
      background: '#F3E5F5',
      text: '#4A148C'
    },
    fontStyle: 'elegant',
    animationType: 'fade',
    interactiveModules: ['gallery'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'Thank you for your endless love, patience, and guidance. You are the best mom in the world.',
    isPremium: false,
    isPublished: true,
    popularity: 90,
    tags: ['mother', 'mom', 'love', 'family'],
    emoji: '👩‍👧',
    previewGradient: 'linear-gradient(135deg, #AB47BC, #CE93D8)'
  },
  {
    id: 'tpl_fam_2',
    slug: 'thank-you-dad',
    title: 'Thank You Dad',
    description: 'A strong, classic template for fathers.',
    occasion: 'family',
    category: 'emotional',
    colorPalette: {
      primary: '#37474F',
      secondary: '#78909C',
      accent: '#CFD8DC',
      background: '#ECEFF1',
      text: '#263238'
    },
    fontStyle: 'bold',
    animationType: 'slide',
    interactiveModules: ['button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'Thanks for always being my rock and my hero. I appreciate everything you do, Dad.',
    isPremium: false,
    isPublished: true,
    popularity: 88,
    tags: ['father', 'dad', 'hero', 'family'],
    emoji: '👨‍👦',
    previewGradient: 'linear-gradient(135deg, #37474F, #78909C)'
  },
  {
    id: 'tpl_fam_3',
    slug: 'family-memories',
    title: 'Family Memories',
    description: 'A scrapbook style layout for the whole family.',
    occasion: 'family',
    category: 'casual',
    colorPalette: {
      primary: '#F57C00',
      secondary: '#FFB74D',
      accent: '#FFE0B2',
      background: '#FFF3E0',
      text: '#E65100'
    },
    fontStyle: 'handwritten',
    animationType: 'fade',
    interactiveModules: ['gallery'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature', 'images'],
    defaultMessage: 'Family is where life begins and love never ends. Cherishing our wonderful times together.',
    isPremium: false,
    isPublished: true,
    popularity: 85,
    tags: ['family', 'scrapbook', 'memories'],
    emoji: '👨‍👩‍👧‍👦',
    previewGradient: 'linear-gradient(135deg, #F57C00, #FFB74D)'
  },
  {
    id: 'tpl_fam_4',
    slug: 'sibling-surprise',
    title: 'Sibling Surprise',
    description: 'A playful template full of sibling banter and love.',
    occasion: 'family',
    category: 'fun',
    colorPalette: {
      primary: '#03A9F4',
      secondary: '#4FC3F7',
      accent: '#B3E5FC',
      background: '#E1F5FE',
      text: '#01579B'
    },
    fontStyle: 'playful',
    animationType: 'bounce',
    interactiveModules: ['scratch'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'We might fight sometimes, but you are still my favorite sibling. Love you!',
    isPremium: false,
    isPublished: true,
    popularity: 81,
    tags: ['sibling', 'brother', 'sister', 'fun'],
    emoji: '🤜🤛',
    previewGradient: 'linear-gradient(135deg, #03A9F4, #4FC3F7)'
  },

  // Festivals
  {
    id: 'tpl_fest_1',
    slug: 'diwali-glow',
    title: 'Diwali Glow',
    description: 'A bright, illuminated template with diyas for Diwali.',
    occasion: 'festival',
    category: 'cultural',
    colorPalette: {
      primary: '#FF5722',
      secondary: '#FF9800',
      accent: '#FFEB3B',
      background: '#212121',
      text: '#FFFDE7'
    },
    fontStyle: 'elegant',
    animationType: 'fade',
    interactiveModules: ['button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'May the festival of lights bring joy, prosperity, and happiness to your home. Happy Diwali!',
    isPremium: false,
    isPublished: true,
    popularity: 97,
    tags: ['diwali', 'festival', 'lights', 'india'],
    emoji: '🪔',
    previewGradient: 'linear-gradient(135deg, #FF5722, #FF9800)'
  },
  {
    id: 'tpl_fest_2',
    slug: 'holi-colors',
    title: 'Holi Colors',
    description: 'A vibrant splash of colors for the festival of Holi.',
    occasion: 'festival',
    category: 'fun',
    colorPalette: {
      primary: '#E91E63',
      secondary: '#9C27B0',
      accent: '#00BCD4',
      background: '#FAFAFA',
      text: '#212121'
    },
    fontStyle: 'playful',
    animationType: 'confetti',
    interactiveModules: ['scratch'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'Wishing you a Holi filled with sweet moments and colorful memories to cherish forever.',
    isPremium: false,
    isPublished: true,
    popularity: 95,
    tags: ['holi', 'festival', 'colors', 'india'],
    emoji: '🎨',
    previewGradient: 'linear-gradient(135deg, #E91E63, #9C27B0)'
  },
  {
    id: 'tpl_fest_3',
    slug: 'eid-celebration',
    title: 'Eid Celebration',
    description: 'A serene and crescent moon themed template for Eid.',
    occasion: 'festival',
    category: 'cultural',
    colorPalette: {
      primary: '#00796B',
      secondary: '#26A69A',
      accent: '#FFD54F',
      background: '#E0F2F1',
      text: '#004D40'
    },
    fontStyle: 'elegant',
    animationType: 'fade',
    interactiveModules: ['envelope'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'Eid Mubarak! May this special day bring peace, happiness, and prosperity to you and your family.',
    isPremium: false,
    isPublished: true,
    popularity: 94,
    tags: ['eid', 'festival', 'moon'],
    emoji: '🌙',
    previewGradient: 'linear-gradient(135deg, #00796B, #26A69A)'
  },
  {
    id: 'tpl_fest_4',
    slug: 'christmas-cheer',
    title: 'Christmas Cheer',
    description: 'Snowflakes and festive red and green for Christmas.',
    occasion: 'festival',
    category: 'festive',
    colorPalette: {
      primary: '#C62828',
      secondary: '#2E7D32',
      accent: '#FFD54F',
      background: '#FAFAFA',
      text: '#111111'
    },
    fontStyle: 'elegant',
    animationType: 'slide',
    interactiveModules: ['button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'Wishing you a Merry Christmas and a season filled with warmth, comfort, and good cheer!',
    isPremium: false,
    isPublished: true,
    popularity: 96,
    tags: ['christmas', 'holiday', 'snow'],
    emoji: '🎄',
    previewGradient: 'linear-gradient(135deg, #C62828, #2E7D32)'
  },
  {
    id: 'tpl_fest_5',
    slug: 'new-year-countdown',
    title: 'New Year Countdown',
    description: 'Sparklers and a fresh look for the New Year.',
    occasion: 'festival',
    category: 'festive',
    colorPalette: {
      primary: '#1A237E',
      secondary: '#3949AB',
      accent: '#FFCA28',
      background: '#E8EAF6',
      text: '#111111'
    },
    fontStyle: 'bold',
    animationType: 'confetti',
    interactiveModules: ['button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'Happy New Year! May the coming year bring you success, joy, and wonderful new opportunities.',
    isPremium: false,
    isPublished: true,
    popularity: 98,
    tags: ['new-year', 'celebration', 'fireworks'],
    emoji: '🎆',
    previewGradient: 'linear-gradient(135deg, #1A237E, #3949AB)'
  },

  // Fun & Interactive
  {
    id: 'tpl_fun_1',
    slug: 'quiz-about-us',
    title: 'Quiz About Us',
    description: 'Test the recipient\'s knowledge about your relationship before seeing the wish.',
    occasion: 'fun',
    category: 'interactive',
    colorPalette: {
      primary: '#673AB7',
      secondary: '#9575CD',
      accent: '#FF4081',
      background: '#EDE7F6',
      text: '#311B92'
    },
    fontStyle: 'playful',
    animationType: 'slide',
    interactiveModules: ['quiz'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'You passed the quiz! Here is my actual message: You are absolutely amazing.',
    isPremium: false,
    isPublished: true,
    popularity: 83,
    tags: ['quiz', 'game', 'interactive'],
    emoji: '🤔',
    previewGradient: 'linear-gradient(135deg, #673AB7, #9575CD)'
  },
  {
    id: 'tpl_fun_2',
    slug: 'spin-the-wheel',
    title: 'Spin the Celebration Wheel',
    description: 'Recipient spins a wheel to get a random mini-wish before the main one.',
    occasion: 'fun',
    category: 'interactive',
    colorPalette: {
      primary: '#FF9800',
      secondary: '#FFCC80',
      accent: '#E91E63',
      background: '#FFF8E1',
      text: '#E65100'
    },
    fontStyle: 'playful',
    animationType: 'bounce',
    interactiveModules: ['button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'You hit the jackpot just by being you. Have a fantastic day!',
    isPremium: false,
    isPublished: true,
    popularity: 80,
    tags: ['wheel', 'game', 'fun'],
    emoji: '🎡',
    previewGradient: 'linear-gradient(135deg, #FF9800, #FFCC80)'
  },
  {
    id: 'tpl_fun_3',
    slug: 'truth-or-dare',
    title: 'Truth or Dare',
    description: 'A daring twist on a greeting card.',
    occasion: 'fun',
    category: 'interactive',
    colorPalette: {
      primary: '#F44336',
      secondary: '#EF9A9A',
      accent: '#2196F3',
      background: '#FFEBEE',
      text: '#B71C1C'
    },
    fontStyle: 'bold',
    animationType: 'slide',
    interactiveModules: ['button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'Truth: You are awesome. Dare: Have the best day ever!',
    isPremium: false,
    isPublished: true,
    popularity: 75,
    tags: ['truth-or-dare', 'game', 'bold'],
    emoji: '🔥',
    previewGradient: 'linear-gradient(135deg, #F44336, #EF9A9A)'
  },
  {
    id: 'tpl_fun_4',
    slug: 'poll-and-vote',
    title: 'Poll and Vote',
    description: 'Start with a funny poll before revealing the wish.',
    occasion: 'fun',
    category: 'interactive',
    colorPalette: {
      primary: '#8BC34A',
      secondary: '#C5E1A5',
      accent: '#FF9800',
      background: '#F1F8E9',
      text: '#33691E'
    },
    fontStyle: 'modern',
    animationType: 'fade',
    interactiveModules: ['poll'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'The votes are in: You are officially the greatest person I know!',
    isPremium: false,
    isPublished: true,
    popularity: 78,
    tags: ['poll', 'vote', 'interactive'],
    emoji: '📊',
    previewGradient: 'linear-gradient(135deg, #8BC34A, #C5E1A5)'
  },
  {
    id: 'tpl_fun_5',
    slug: 'mystery-message',
    title: 'Mystery Message',
    description: 'A message that decodes itself beautifully on screen.',
    occasion: 'fun',
    category: 'reveal',
    colorPalette: {
      primary: '#607D8B',
      secondary: '#B0BEC5',
      accent: '#4CAF50',
      background: '#ECEFF1',
      text: '#263238'
    },
    fontStyle: 'modern',
    animationType: 'fade',
    interactiveModules: ['button'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'I could not keep this a secret any longer... You are simply the best!',
    isPremium: false,
    isPublished: true,
    popularity: 86,
    tags: ['mystery', 'decode', 'secret'],
    emoji: '🕵️',
    previewGradient: 'linear-gradient(135deg, #607D8B, #B0BEC5)'
  },
  {
    id: 'tpl_fun_6',
    slug: 'scratch-to-reveal',
    title: 'Scratch-to-Reveal',
    description: 'Swipe to scratch off the foil and reveal the hidden message.',
    occasion: 'fun',
    category: 'reveal',
    colorPalette: {
      primary: '#9E9E9E',
      secondary: '#E0E0E0',
      accent: '#E91E63',
      background: '#FAFAFA',
      text: '#212121'
    },
    fontStyle: 'bold',
    animationType: 'fade',
    interactiveModules: ['scratch'] as InteractionType[],
    supportedFields: ['title', 'message', 'signature'],
    defaultMessage: 'Surprise! Hope this brightens up your day like you brighten mine.',
    isPremium: false,
    isPublished: true,
    popularity: 92,
    tags: ['scratch', 'reveal', 'interactive'],
    emoji: '🪙',
    previewGradient: 'linear-gradient(135deg, #9E9E9E, #E0E0E0)'
  }
];
